/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import * as THREE from 'three'

import CustomShaderMaterial from 'three-custom-shader-material'
import { Card } from './Card'

import cardVertexShader from '../../shaders/card/vertex.glsl'
import cardFragmentShader from '../../shaders/card/fragment.glsl'
import { Float } from '@react-three/drei'

export default function Model(props) {
    const { nodes, materials } = useGLTF('./models/card.glb')
    return <>

        <group position={ [ 0,0,0 ] }>
            <Float>
                <group scale={0.4}>
                    <mesh
                        geometry={nodes.Front.geometry}
                        position={[0, 0, 0.01]}
                        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                        scale={[3.5, 1, 2.5]}
                    >
                        <CustomShaderMaterial
                            baseMaterial={ THREE.MeshStandardMaterial }
                            vertexShader={ cardVertexShader }
                            fragmentShader={ cardFragmentShader }
                            side={THREE.DoubleSide}
                        />
                    </mesh>
                </group>
            </Float>
        </group>

    </>
}

useGLTF.preload('/card.glb')